workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      vars:
        LC_ALL: en_US.UTF-8
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_app
          flutter packages pub get
      - name: Install pods
        script: |
          cd flutter_app/ios
          pod install
          cd ..
      - name: Flutter analyze
        script: |
          cd flutter_app
          flutter analyze
      - name: Flutter unit tests
        script: |
          cd flutter_app
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: |
          cd flutter_app
          flutter build ipa --release
    artifacts:
      - flutter_app/build/ios/ipa/*.ipa
